# This file was generated by GoReleaser. DO NOT EDIT.
cask "dnscontrol" do
  name "dnscontrol"
  desc "DNSControl: Infrastructure as Code for DNS Zones"
  homepage "https://docs.dnscontrol.org/"
  version "4.36.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dnscontrol"

  on_macos do
    url "https://github.com/StackExchange/dnscontrol/releases/download/v#{version}/dnscontrol_#{version}_darwin_all.tar.gz"
    sha256 "37ec00ed9c48396d6b6d3a6e8bbeb296d94d32089ab9106b7225773a3e65dc27"
  end

  on_linux do
    on_intel do
      url "https://github.com/StackExchange/dnscontrol/releases/download/v#{version}/dnscontrol_#{version}_linux_amd64.tar.gz"
      sha256 "29cec0a8b00cda37149d5ee86d8da91b11f01b7e5f37ac06ae63c88b01f4071a"
    end
    on_arm do
      url "https://github.com/StackExchange/dnscontrol/releases/download/v#{version}/dnscontrol_#{version}_linux_arm64.tar.gz"
      sha256 "e53ca93dfcecf119919b7fa0d732071d497cf546a6df454b3263214ea0dfd0bc"
    end
  end

  # No zap stanza required
end
