# This file was generated by GoReleaser. DO NOT EDIT.
cask "dnscontrol" do
  name "dnscontrol"
  desc "DNSControl: Infrastructure as Code for DNS Zones"
  homepage "https://docs.dnscontrol.org/"
  version "4.34.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dnscontrol"

  on_macos do
    url "https://github.com/StackExchange/dnscontrol/releases/download/v#{version}/dnscontrol_#{version}_darwin_all.tar.gz"
    sha256 "8e782151f943630b708cc5c5cd7ed94daff20b78e57768a4b391380a64dd4ac0"
  end

  on_linux do
    on_intel do
      url "https://github.com/StackExchange/dnscontrol/releases/download/v#{version}/dnscontrol_#{version}_linux_amd64.tar.gz"
      sha256 "448edaf936a396cc7dd81223481b01908b03aad8b831a6b68477335f85b2836c"
    end
    on_arm do
      url "https://github.com/StackExchange/dnscontrol/releases/download/v#{version}/dnscontrol_#{version}_linux_arm64.tar.gz"
      sha256 "e3b12325459ef9b439d602845c0ea0930066fe325900b95cc59d1077ceee7f1a"
    end
  end

  # No zap stanza required
end
