# This file was generated by GoReleaser. DO NOT EDIT.
cask "dnscontrol" do
  name "dnscontrol"
  desc "DNSControl: Infrastructure as Code for DNS Zones"
  homepage "https://docs.dnscontrol.org/"
  version "4.35.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dnscontrol"

  on_macos do
    url "https://github.com/StackExchange/dnscontrol/releases/download/v#{version}/dnscontrol_#{version}_darwin_all.tar.gz"
    sha256 "ba2cb9ec7722b6be5a2d3eca7082f0ff988b22b52fe510d23196858a78c686d1"
  end

  on_linux do
    on_intel do
      url "https://github.com/StackExchange/dnscontrol/releases/download/v#{version}/dnscontrol_#{version}_linux_amd64.tar.gz"
      sha256 "510b9bccf6544b8739625bc1e2090598fcf3ef7e8d522b87749847111fa9e0dc"
    end
    on_arm do
      url "https://github.com/StackExchange/dnscontrol/releases/download/v#{version}/dnscontrol_#{version}_linux_arm64.tar.gz"
      sha256 "43ac324c1e35d7d182dceaf5c01267643ff631541154592d8475e9bf276398c5"
    end
  end

  # No zap stanza required
end
